<?php

use Drupal\Component\Utility\Html;

/**
 * @file
 * Primary module hooks for drupalcamp2022_block module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */


/**
 * Implements hook_theme().
 */
function drupalcamp2022_block_theme($existing, $type, $theme, $path) {
  return [
    'drupalcamp2022_card' => [
      'variables' => [
        'name' => NULL,
        'border' => FALSE,
        'icon' => FALSE
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_drupalcamp2022_card().
 */
function template_preprocess_drupalcamp2022_card(&$variables) {
  $variables['attributes']['id'] = Html::getUniqueId('simpleblock');
  $variables['attributes']['data-type'] = 'simple-block';
}
