# Schema for the configuration files of the Basic Theme theme.
basic_theme.settings:
  type: theme_settings
  label: 'Basic Theme settings'
  mapping:
    font_size:
      type: integer
      label: Font size
